apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        image: teokyllc.azurecr.io/argocd:latest
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
      automountServiceAccountToken: true
